Fix FTBFS when szip is enabled.
/usr/bin/ld: ../../hdf/src/.libs/libdf.so: undefined reference to `SZ_encoder_enabled'
/usr/bin/ld: ../../hdf/src/.libs/libdf.so: undefined reference to `SZ_BufftoBuffCompress'
/usr/bin/ld: ../../hdf/src/.libs/libdf.so: undefined reference to `SZ_BufftoBuffDecompress'

/usr/bin/ld: hrepack_parse.o: undefined reference to symbol 'SZ_encoder_enabled'
/usr/bin/ld: /lib/x86_64-linux-gnu/libsz.so.2: error adding symbols: DSO missing from command line

/usr/bin/ld: hrepacktst.o: undefined reference to symbol 'SZ_encoder_enabled'
/usr/bin/ld: /lib/x86_64-linux-gnu/libsz.so.2: error adding symbols: DSO missing from command line